### ISSUE TITLE
Terminology: gateway v.s. distributed executor

### ISSUE THREAD

**Issue by SimonSapin** [graphql/composite-schemas-spec#22]
The term "gateway" is use a few times across this repository. For example:

https://github.com/graphql/composite-schemas-spec/blob/aaf454b186184e7e7fe7000aefd41169f747c4dd/spec/Section%201%20--%20Overview.md#L43-L45

Based on the existence of `@apollo/gateway` I can guess it is used interchangeably with "distributed (GraphQL) executor", which has a proper definition in the Overview. I suggest using "execution" or "distributed executor" everywhere. (No need to repeat "GraphQL" every time, this being a document of the GraphQL WG.)

**Comment by benjie** [comment]
Agree that we should standardize on terminology and use the same terms everywhere - we can use spec-md's definitions feature to link to the definition of the word.

This may be a duplicate of https://github.com/graphql/composite-schemas-spec/issues/17 where the correct term to use is under discussion?

**Comment by SimonSapin** [comment]
Indeed, closing as duplicate of https://github.com/graphql/composite-schemas-spec/issues/17
